- Pytorch is built around a computation graph composed of a set of nodes.
- Tensors are similar to numpy's array, except that tensors are optimized for automatic differentiation and can run on GPUs
- CPU vs GPU:

<img src='images/cpu_vs_gpu.png' width=500>

#### Basic Pytorch

In [8]:
# create tensor
import torch
import numpy as np

np.set_printoptions(precision=3)

a = [1,2,3]
b = np.array([4,5,6], dtype=np.int32)

tensor_a = torch.tensor(a)
tensor_b = torch.tensor(b)

print(tensor_a, tensor_a.dtype)
print(tensor_b)

tensor([1, 2, 3]) torch.int64
tensor([4, 5, 6], dtype=torch.int32)


In [9]:
# create 1s or 0s tensor
t_ones = torch.ones(2, 3)
t_zeros = torch.zeros(2,3)
print(t_ones)
print(t_zeros)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [10]:
# create random tensor
t_rand = torch.rand(2,3)
print(t_rand)

tensor([[0.3822, 0.0670, 0.8347],
        [0.9397, 0.2339, 0.7952]])


In [11]:
# data type and shape of a tensor_a
print(tensor_a.dtype)
tensor_a_new = tensor_a.to(torch.int32)
print(tensor_a_new.dtype)

torch.int64
torch.int32


In [12]:
# transpose
t_rand_new = torch.transpose(t_rand, 1, 0)
print(t_rand_new)

tensor([[0.3822, 0.9397],
        [0.0670, 0.2339],
        [0.8347, 0.7952]])


In [13]:
# reshape
t_zero = torch.zeros(3, 6)
print(t_zero)
t_zero_transpose = t_zero.transpose(1, 0)
print(t_zero_transpose)
t_zero_reshape = t_zero.reshape(-1, 2)
t_zero_reshape_2 = torch.reshape(t_zero, (9, 2))
print(t_zero_reshape)
print(t_zero_reshape_2)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [14]:
# remove dimension: (can only remove dimensions that have size 1)
t = torch.zeros(2,1,2)
print(t, t.shape)
t_squeeze = torch.squeeze(t, 1)
print()
print(t_squeeze, t_squeeze.shape)

tensor([[[0., 0.]],

        [[0., 0.]]]) torch.Size([2, 1, 2])

tensor([[0., 0.],
        [0., 0.]]) torch.Size([2, 2])


In [15]:
# add new dimension
t = torch.zeros(2,3)
print(t, t.shape)
t_unsqueeze = torch.unsqueeze(t, 2)
print(t_unsqueeze, t_unsqueeze.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) torch.Size([2, 3])
tensor([[[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]]]) torch.Size([2, 3, 1])


In [16]:
# apply mathematical operations:
torch.manual_seed(1)
t1 = 2*torch.rand(5,2) - 1 # uniform distribution from [0,1] -> 2 * [0, 1]  - 1 = [-1, 1]
t2 = torch.normal(mean=0, std=1, size=(5, 2))
print(t1)
print(t2)

tensor([[ 0.5153, -0.4414],
        [-0.1939,  0.4694],
        [-0.9414,  0.5997],
        [-0.2057,  0.5087],
        [ 0.1390, -0.1224]])
tensor([[ 0.8590,  0.7056],
        [-0.3406, -1.2720],
        [-1.1948,  0.0250],
        [-0.7627,  1.3969],
        [-0.3245,  0.2879]])


In [17]:
# element-wise product:
t3 = torch.multiply(t1, t2)
print(t3)
# dot product
t4 = torch.matmul(t1, t2.T)
print(t4)
# mean
t5 = torch.mean(t3, axis=1)
print(t5)

tensor([[ 0.4426, -0.3114],
        [ 0.0660, -0.5970],
        [ 1.1249,  0.0150],
        [ 0.1569,  0.7107],
        [-0.0451, -0.0352]])
tensor([[ 0.1312,  0.3860, -0.6267, -1.0096, -0.2943],
        [ 0.1647, -0.5310,  0.2434,  0.8035,  0.1980],
        [-0.3855, -0.4422,  1.1399,  1.5558,  0.4781],
        [ 0.1822, -0.5771,  0.2585,  0.8676,  0.2132],
        [ 0.0330,  0.1084, -0.1692, -0.2771, -0.0804]])
tensor([ 0.0656, -0.2655,  0.5699,  0.4338, -0.0402])


In [18]:
t3 = -torch.ones(2, 3)
print(t3)

# compute linalg norm P
norm_t1 = torch.linalg.norm(t3, ord=1, dim=1)
print(norm_t1)

norm_t2 = torch.linalg.norm(t3, ord=2, dim=0)
print(norm_t2)

tensor([[-1., -1., -1.],
        [-1., -1., -1.]])
tensor([3., 3.])
tensor([1.4142, 1.4142, 1.4142])


In [19]:
# split
torch.manual_seed(1)
t = torch.rand(6)
print(t)

# split to chunks of 3
t_split = t.split(3)
print(t_split)

# create 3 chunks
t_chunk = t.chunk(3)
print(t_chunk)

tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293, 0.7999])
(tensor([0.7576, 0.2793, 0.4031]), tensor([0.7347, 0.0293, 0.7999]))
(tensor([0.7576, 0.2793]), tensor([0.4031, 0.7347]), tensor([0.0293, 0.7999]))


In [25]:
# concatenate
A = torch.ones(3)
B = torch.zeros(2)
C = torch.concatenate([A, B], axis=0) # same as cat()
print(C)

# stack
D = torch.zeros(3)
S = torch.stack([A, D], axis=0)
print(S)

tensor([1., 1., 1., 0., 0.])
tensor([[1., 1., 1.],
        [0., 0., 0.]])
